app = "the-archivist"

[build]
  dockerfile = "Dockerfile"

[env]
  # Не указываем тут токен, лучше добавить через команду fly secrets set BOT_TOKEN=твой_токен
  # но если хочешь, можно прописать напрямую:
  # BOT_TOKEN = "твой_токен_сюда"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.http_checks]]
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "30s"