app = "the-archivist"

[build]
  dockerfile = "Dockerfile"

[env]
  # Не указываем тут токен, лучше добавить через команду fly secrets set BOT_TOKEN=твой_токен
  # но если хочешь, можно прописать напрямую:
  # BOT_TOKEN = "твой_токен_сюда"

